"""Queued cache misses must reuse audio generated by the preceding job."""

import asyncio
from unittest.mock import AsyncMock, MagicMock

import pytest

from galgame2voice.database.session import init_db
from galgame2voice.services.tts_cache_manager import TtsCacheManager
from galgame2voice.services.tts_scheduler import TtsScheduler
from galgame2voice.services.tts_service import TtsService
from galgame2voice.services.tts_options import resolve_tts_options


@pytest.fixture
async def synthesis_stack(tmp_path, monkeypatch):
    monkeypatch.setenv("GALGAME2VOICE_PROJECT_ROOT", str(tmp_path))
    db_path = tmp_path / "test.db"
    monkeypatch.setenv("GALGAME2VOICE_DB_PATH", str(db_path))
    await init_db(db_path)
    scheduler = TtsScheduler()
    monkeypatch.setattr("galgame2voice.services.tts_service.get_tts_scheduler", lambda: scheduler)
    cache = TtsCacheManager(cache_dir=tmp_path / "cache", db_path=str(db_path))
    client = MagicMock()
    # Cache persistence accepts opaque audio bytes; no real engine is needed.
    audio = b"RIFF" + b"audible-test-audio" * 16
    started, release = asyncio.Event(), asyncio.Event()

    async def synthesize(*args, **kwargs):
        started.set()
        await release.wait()
        return audio

    client.synthesize = AsyncMock(side_effect=synthesize)
    service = TtsService(client=client, cache_manager=cache, audio_dir=tmp_path)
    yield service, scheduler, cache, client, audio, started, release
    release.set()
    await scheduler.aclose()
    await cache.aclose()


async def _wait_queued(scheduler, count):
    async def wait():
        # The scheduler exposes queue depth, but no enqueue event to await.
        while scheduler.get_queue_depth() < count:  # noqa: ASYNC110
            await asyncio.sleep(0)
    await asyncio.wait_for(wait(), timeout=3)


@pytest.mark.parametrize("mode", ["bytes", "file", "mixed"])
async def test_identical_burst_runs_one_inference(synthesis_stack, mode):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    calls = []
    for i in range(16):
        method = service.synthesize if mode == "bytes" or (mode == "mixed" and i % 2 == 0) else service.synthesize_to_file
        calls.append(asyncio.create_task(method(
            "こんにちは。", options={"_pre_resolved": True, "_generation_id": f"turn-{i}"},
        )))
    try:
        await asyncio.wait_for(started.wait(), timeout=3)
        await _wait_queued(scheduler, len(calls) - 1)
        release.set()
        results = await asyncio.wait_for(asyncio.gather(*calls), timeout=5)
        assert client.synthesize.await_count == 1, "queued cache misses repeated the same GPU inference"
        for result in results:
            if isinstance(result, bytes):
                assert result == audio
            else:
                url, path, size = result
                assert url.startswith("/audio/cache/")
                assert path.read_bytes() == audio
                assert size == len(audio)
    finally:
        release.set()
        for call in calls:
            call.cancel()
        await asyncio.gather(*calls, return_exceptions=True)


async def test_disabled_cache_preserves_independent_synthesis(synthesis_stack):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    calls = [asyncio.create_task(service.synthesize(
        "こんにちは。", options={"_pre_resolved": True}, use_cache=False,
    )) for _ in range(4)]
    await asyncio.wait_for(started.wait(), timeout=3)
    await _wait_queued(scheduler, 3)
    release.set()
    assert await asyncio.wait_for(asyncio.gather(*calls), timeout=5) == [audio] * 4
    assert client.synthesize.await_count == 4


@pytest.mark.parametrize("name,values", [
    ("speed", (0.8, 1.2)),
    ("temp", (0.7, 1.1)),
    ("preset", ("high_quality", "low_latency")),
])
async def test_distinct_voice_parameters_are_not_reused(synthesis_stack, name, values):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    calls = [asyncio.create_task(service.synthesize(
        "こんにちは。", options={"_pre_resolved": True, name: value},
    )) for value in values]
    await asyncio.wait_for(started.wait(), timeout=3)
    await _wait_queued(scheduler, 1)
    release.set()
    assert await asyncio.wait_for(asyncio.gather(*calls), timeout=5) == [audio, audio]
    assert client.synthesize.await_count == 2


@pytest.mark.parametrize("options", [
    {"speed": 0.8}, {"temp": 0.7}, {"preset": "high_quality"},
    {"preset": "low_latency"}, {"how_to_cut": "cut1", "cut_option": "cut3"},
])
async def test_cache_identity_matches_resolved_inference_parameters(synthesis_stack, options):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    effective = service._sanitize_dynamic_voice_options(dict(options), text="こんにちは。")
    resolved = resolve_tts_options(effective)
    assert cache.compute_cache_key("こんにちは。", options=effective) == cache.compute_cache_key(
        "こんにちは。", options=resolved,
    ), "cache identity disagreed with the parameters sent to the engine"


async def test_distinct_profile_ids_have_distinct_cache_entries(synthesis_stack):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    keys = [cache.compute_cache_key("こんにちは。", options={"voice_profile_id": id_})[0] for id_ in (1, 2)]
    assert keys[0] != keys[1], "different characters shared a cache entry when weight metadata was absent"


async def test_legacy_ambiguous_cache_is_not_reused(synthesis_stack):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    # Recorded from v1 for this text: both default speed and speed=0.8 produced
    # this same key, so its contents cannot be assumed to match default speed.
    legacy_key = "0c206f306c32d0b3398f679632dd12cef14c64071f627c24c88af006b8eafd2f"
    old_audio = b"RIFF" + b"wrong-speed-legacy-audio" * 16
    _, old_path, _ = await cache.put(
        cache_key=legacy_key, text="こんにちは。", clean_text="こんにちは。",
        voice_profile_id=1, params_hash="legacy", audio_bytes=old_audio,
    )
    assert await cache.get(legacy_key) is not None
    release.set()
    assert await service.synthesize("こんにちは。", options={"_pre_resolved": True}) == audio
    client.synthesize.assert_awaited_once()
    assert old_path.read_bytes() == old_audio, "old history audio must remain playable"


@pytest.mark.parametrize("method_name", ["synthesize", "synthesize_to_file"])
async def test_execution_recheck_does_not_double_count_cache_misses(synthesis_stack, method_name):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    method = getattr(service, method_name)
    release.set()
    for _ in range(9):
        await method("こんにちは。", options={"_pre_resolved": True})
    stats = await cache.get_stats()
    assert stats["total_misses"] == 1
    assert stats["total_hits"] == 8
    client.synthesize.assert_awaited_once()


async def test_cancelled_generation_does_not_cancel_another_caller(synthesis_stack):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    first = asyncio.create_task(service.synthesize(
        "こんにちは。", options={"_pre_resolved": True, "_generation_id": "old"},
    ))
    await asyncio.wait_for(started.wait(), timeout=3)
    second = asyncio.create_task(service.synthesize(
        "こんにちは。", options={"_pre_resolved": True, "_generation_id": "new"},
    ))
    await _wait_queued(scheduler, 1)
    assert scheduler.cancel_generation("old") == 1
    release.set()
    with pytest.raises(asyncio.CancelledError):
        await first
    assert await asyncio.wait_for(second, timeout=5) == audio
    assert client.synthesize.await_count == 2


async def test_failed_inference_does_not_poison_queued_request(synthesis_stack):
    service, scheduler, cache, client, audio, started, release = synthesis_stack
    async def fail_first(*args, **kwargs):
        started.set()
        await release.wait()
        if client.synthesize.await_count == 1:
            raise RuntimeError("first synthesis failed")
        return audio
    client.synthesize.side_effect = fail_first
    calls = [asyncio.create_task(service.synthesize_to_file(
        "こんにちは。", options={"_pre_resolved": True},
    )) for _ in range(2)]
    await asyncio.wait_for(started.wait(), timeout=3)
    await _wait_queued(scheduler, 1)
    release.set()
    results = await asyncio.wait_for(asyncio.gather(*calls, return_exceptions=True), timeout=5)
    assert isinstance(results[0], RuntimeError)
    assert results[1][1].read_bytes() == audio
    assert client.synthesize.await_count == 2
