"""
Backward-compatible facade for SQLite persistence operations in galgame2voice.

This module re-exports operations from domain-specific modules in
`galgame2voice.database.crud_modules` as well as schema migrations
from `galgame2voice.database.migrations`.

All historical signatures and module attributes remain 100% backward-compatible.
"""

import logging

from galgame2voice.database.crud_modules.memory_affection import (
    _format_affection_response,
    calculate_affection_level,
    clear_memories,
    create_memory,
    delete_memory,
    get_character_affection,
    get_memory,
    get_or_create_character_affection,
    increment_affection,
    list_memories,
    record_memory_recall,
    record_memory_recall_batch,
    reset_character_affection,
    unlock_character_dialogues,
    update_character_affection,
    update_memory,
    upsert_memory,
)
from galgame2voice.database.crud_modules.providers import (
    create_provider,
    delete_provider,
    get_active_provider,
    get_active_provider_raw,
    get_provider,
    get_provider_raw,
    is_masked_key,
    list_providers,
    mask_api_key,
    mask_custom_headers,
    set_active_provider,
    update_provider,
)
from galgame2voice.database.crud_modules.sessions import (
    add_message,
    clear_session_messages,
    count_session_messages,
    delete_session,
    get_or_create_session,
    get_recent_messages,
    get_session,
    list_sessions,
    list_sessions_overview,
    upsert_session,
)
from galgame2voice.database.crud_modules.settings_cache import (
    clean_tts_cache_lru,
    clear_all_tts_cache_entries,
    delete_tts_cache_entry,
    get_metrics_overview,
    get_oldest_tts_cache_entries,
    get_provider_metrics_breakdown,
    get_recent_latency_trends,
    get_settings,
    get_settings_raw,
    get_tts_cache_entry,
    get_tts_cache_stats,
    insert_token_metric,
    record_tts_cache_hit,
    record_tts_cache_miss,
    touch_tts_cache_entry,
    batch_touch_tts_cache_entries,
    update_settings,
    upsert_tts_cache_entry,
    verify_console_token,
)
from galgame2voice.database.crud_modules.voice_profiles import (
    create_voice_profile,
    delete_voice_profile,
    get_active_voice_profile,
    get_voice_profile,
    get_voice_profile_by_name,
    list_voice_profiles,
    set_active_voice_profile,
    update_voice_profile,
)
from galgame2voice.database.migrations import (
    CURRENT_SCHEMA_VERSION,
    _DEFAULT_REF_AUDIO,
    _DEFAULT_REF_TEXT,
    _add_column_if_missing,
    _get_table_columns,
    _migration_v1_base_schema,
    _migration_v2_columns,
    _migration_v3_security_and_indexes,
    _migration_v4_prompts_and_self_healing,
    _migration_v5_precision_and_column_integrity,
    _migration_v6_session_titles_and_settings,
    auto_heal_voice_profiles,
    init_schema_and_seeds,
    run_schema_migrations,
)

logger = logging.getLogger("galgame2voice.database.crud")

__all__ = [
    # Schema migrations & helpers
    "CURRENT_SCHEMA_VERSION",
    "run_schema_migrations",
    "init_schema_and_seeds",
    "auto_heal_voice_profiles",
    "_get_table_columns",
    "_add_column_if_missing",
    "_migration_v1_base_schema",
    "_migration_v2_columns",
    "_migration_v3_security_and_indexes",
    "_migration_v4_prompts_and_self_healing",
    "_migration_v5_precision_and_column_integrity",
    "_migration_v6_session_titles_and_settings",
    "_DEFAULT_REF_AUDIO",
    "_DEFAULT_REF_TEXT",
    # Providers
    "mask_api_key",
    "is_masked_key",
    "mask_custom_headers",
    "list_providers",
    "get_provider",
    "get_provider_raw",
    "get_active_provider",
    "get_active_provider_raw",
    "create_provider",
    "update_provider",
    "set_active_provider",
    "delete_provider",
    # Voice Profiles
    "list_voice_profiles",
    "get_voice_profile",
    "get_voice_profile_by_name",
    "get_active_voice_profile",
    "create_voice_profile",
    "update_voice_profile",
    "set_active_voice_profile",
    "delete_voice_profile",
    # Sessions
    "get_or_create_session",
    "get_session",
    "list_sessions",
    "list_sessions_overview",
    "upsert_session",
    "delete_session",
    "clear_session_messages",
    "add_message",
    "get_recent_messages",
    "count_session_messages",
    # Memory & Affection
    "create_memory",
    "get_memory",
    "list_memories",
    "update_memory",
    "delete_memory",
    "clear_memories",
    "upsert_memory",
    "record_memory_recall",
    "record_memory_recall_batch",
    "calculate_affection_level",
    "_format_affection_response",
    "get_or_create_character_affection",
    "get_character_affection",
    "update_character_affection",
    "reset_character_affection",
    "unlock_character_dialogues",
    "increment_affection",
    # Settings & TTS Cache
    "get_settings",
    "get_settings_raw",
    "update_settings",
    "verify_console_token",
    "get_tts_cache_entry",
    "touch_tts_cache_entry",
    "batch_touch_tts_cache_entries",
    "upsert_tts_cache_entry",
    "delete_tts_cache_entry",
    "get_oldest_tts_cache_entries",
    "get_tts_cache_stats",
    "clear_all_tts_cache_entries",
    "record_tts_cache_hit",
    "record_tts_cache_miss",
    "clean_tts_cache_lru",
    "insert_token_metric",
    "get_metrics_overview",
    "get_provider_metrics_breakdown",
    "get_recent_latency_trends",
    # Module logger
    "logger",
]
